server:
  port: 1000

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: root
    #password: Dusgmlxhrl1!
    url: jdbc:mysql://uplus3-rds.cm7qbaqeb5q4.ap-northeast-2.rds.amazonaws.com:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: uplus3zzangzzang


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      format_sql: true
      ddl-auto: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.38.54.131:8761/eureka/ # localhost 3.38.100.161





