server:
  port: 1000

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://3.36.55.65:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: admin
    #password: uplus3zzangzzang
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Dusgmlxhrl1!


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      format_sql: true
      ddl-auto: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # localhost 3.38.100.161





